/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root.tsx'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardRouteImport } from './routes/dashboard.tsx'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index.tsx'
import { Route as DashboardAdminRouteImport } from './routes/dashboard.admin.tsx'
import { Route as DashboardHashtagRouteImport } from './routes/dashboard.hashtag.tsx'
import { Route as DashboardTemplatesRouteImport } from './routes/dashboard.templates.tsx'
import { Route as DashboardTopPlayersRouteImport } from './routes/dashboard.top-players.tsx'
import { Route as DashboardTranscricaoRouteImport } from './routes/dashboard.transcricao.tsx'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAdminRoute = DashboardAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardHashtagRoute = DashboardHashtagRouteImport.update({
  id: '/hashtag',
  path: '/hashtag',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTemplatesRoute = DashboardTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTopPlayersRoute = DashboardTopPlayersRouteImport.update({
  id: '/top-players',
  path: '/top-players',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTranscricaoRoute = DashboardTranscricaoRouteImport.update({
  id: '/transcricao',
  path: '/transcricao',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/dashboard/admin': typeof DashboardAdminRoute
  '/dashboard/hashtag': typeof DashboardHashtagRoute
  '/dashboard/templates': typeof DashboardTemplatesRoute
  '/dashboard/top-players': typeof DashboardTopPlayersRoute
  '/dashboard/transcricao': typeof DashboardTranscricaoRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard/admin': typeof DashboardAdminRoute
  '/dashboard/hashtag': typeof DashboardHashtagRoute
  '/dashboard/templates': typeof DashboardTemplatesRoute
  '/dashboard/top-players': typeof DashboardTopPlayersRoute
  '/dashboard/transcricao': typeof DashboardTranscricaoRoute
  '/dashboard': typeof DashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/dashboard/admin': typeof DashboardAdminRoute
  '/dashboard/hashtag': typeof DashboardHashtagRoute
  '/dashboard/templates': typeof DashboardTemplatesRoute
  '/dashboard/top-players': typeof DashboardTopPlayersRoute
  '/dashboard/transcricao': typeof DashboardTranscricaoRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
  | '/'
  | '/dashboard'
  | '/dashboard/admin'
  | '/dashboard/hashtag'
  | '/dashboard/templates'
  | '/dashboard/top-players'
  | '/dashboard/transcricao'
  | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
  | '/'
  | '/dashboard/admin'
  | '/dashboard/hashtag'
  | '/dashboard/templates'
  | '/dashboard/top-players'
  | '/dashboard/transcricao'
  | '/dashboard'
  id:
  | '__root__'
  | '/'
  | '/dashboard'
  | '/dashboard/admin'
  | '/dashboard/hashtag'
  | '/dashboard/templates'
  | '/dashboard/top-players'
  | '/dashboard/transcricao'
  | '/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/admin': {
      id: '/dashboard/admin'
      path: '/admin'
      fullPath: '/dashboard/admin'
      preLoaderRoute: typeof DashboardAdminRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/hashtag': {
      id: '/dashboard/hashtag'
      path: '/hashtag'
      fullPath: '/dashboard/hashtag'
      preLoaderRoute: typeof DashboardHashtagRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/templates': {
      id: '/dashboard/templates'
      path: '/templates'
      fullPath: '/dashboard/templates'
      preLoaderRoute: typeof DashboardTemplatesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/top-players': {
      id: '/dashboard/top-players'
      path: '/top-players'
      fullPath: '/dashboard/top-players'
      preLoaderRoute: typeof DashboardTopPlayersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/transcricao': {
      id: '/dashboard/transcricao'
      path: '/transcricao'
      fullPath: '/dashboard/transcricao'
      preLoaderRoute: typeof DashboardTranscricaoRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardAdminRoute: typeof DashboardAdminRoute
  DashboardHashtagRoute: typeof DashboardHashtagRoute
  DashboardTemplatesRoute: typeof DashboardTemplatesRoute
  DashboardTopPlayersRoute: typeof DashboardTopPlayersRoute
  DashboardTranscricaoRoute: typeof DashboardTranscricaoRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAdminRoute: DashboardAdminRoute,
  DashboardHashtagRoute: DashboardHashtagRoute,
  DashboardTemplatesRoute: DashboardTemplatesRoute,
  DashboardTopPlayersRoute: DashboardTopPlayersRoute,
  DashboardTranscricaoRoute: DashboardTranscricaoRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
