/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as TermosRouteImport } from './routes/termos'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardAdminRouteImport } from './routes/dashboard.admin'
import { Route as DashboardConfiguracoesRouteImport } from './routes/dashboard.configuracoes'
import { Route as DashboardHashtagRouteImport } from './routes/dashboard.hashtag'
import { Route as DashboardMelhoresMomentosRouteImport } from './routes/dashboard.melhores-momentos'
import { Route as DashboardPlanosRouteImport } from './routes/dashboard.planos'
import { Route as DashboardTemplatesRouteImport } from './routes/dashboard.templates'
import { Route as DashboardTopPlayersRouteImport } from './routes/dashboard.top-players'
import { Route as DashboardTranscricaoRouteImport } from './routes/dashboard.transcricao'
import { Route as DashboardConfiguracoesTiktokCallbackRouteImport } from './routes/dashboard.configuracoes.tiktok.callback'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const TermosRoute = TermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAdminRoute = DashboardAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardConfiguracoesRoute = DashboardConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardHashtagRoute = DashboardHashtagRouteImport.update({
  id: '/hashtag',
  path: '/hashtag',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMelhoresMomentosRoute =
  DashboardMelhoresMomentosRouteImport.update({
    id: '/melhores-momentos',
    path: '/melhores-momentos',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardPlanosRoute = DashboardPlanosRouteImport.update({
  id: '/planos',
  path: '/planos',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTemplatesRoute = DashboardTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTopPlayersRoute = DashboardTopPlayersRouteImport.update({
  id: '/top-players',
  path: '/top-players',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTranscricaoRoute = DashboardTranscricaoRouteImport.update({
  id: '/transcricao',
  path: '/transcricao',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardConfiguracoesTiktokCallbackRoute =
  DashboardConfiguracoesTiktokCallbackRouteImport.update({
    id: '/tiktok/callback',
    path: '/tiktok/callback',
    getParentRoute: () => DashboardConfiguracoesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/privacidade': typeof PrivacidadeRoute
  '/termos': typeof TermosRoute
  '/dashboard/admin': typeof DashboardAdminRoute
  '/dashboard/configuracoes': typeof DashboardConfiguracoesRouteWithChildren
  '/dashboard/hashtag': typeof DashboardHashtagRoute
  '/dashboard/melhores-momentos': typeof DashboardMelhoresMomentosRoute
  '/dashboard/planos': typeof DashboardPlanosRoute
  '/dashboard/templates': typeof DashboardTemplatesRoute
  '/dashboard/top-players': typeof DashboardTopPlayersRoute
  '/dashboard/transcricao': typeof DashboardTranscricaoRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/configuracoes/tiktok/callback': typeof DashboardConfiguracoesTiktokCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/privacidade': typeof PrivacidadeRoute
  '/termos': typeof TermosRoute
  '/dashboard/admin': typeof DashboardAdminRoute
  '/dashboard/configuracoes': typeof DashboardConfiguracoesRouteWithChildren
  '/dashboard/hashtag': typeof DashboardHashtagRoute
  '/dashboard/melhores-momentos': typeof DashboardMelhoresMomentosRoute
  '/dashboard/planos': typeof DashboardPlanosRoute
  '/dashboard/templates': typeof DashboardTemplatesRoute
  '/dashboard/top-players': typeof DashboardTopPlayersRoute
  '/dashboard/transcricao': typeof DashboardTranscricaoRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/configuracoes/tiktok/callback': typeof DashboardConfiguracoesTiktokCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/privacidade': typeof PrivacidadeRoute
  '/termos': typeof TermosRoute
  '/dashboard/admin': typeof DashboardAdminRoute
  '/dashboard/configuracoes': typeof DashboardConfiguracoesRouteWithChildren
  '/dashboard/hashtag': typeof DashboardHashtagRoute
  '/dashboard/melhores-momentos': typeof DashboardMelhoresMomentosRoute
  '/dashboard/planos': typeof DashboardPlanosRoute
  '/dashboard/templates': typeof DashboardTemplatesRoute
  '/dashboard/top-players': typeof DashboardTopPlayersRoute
  '/dashboard/transcricao': typeof DashboardTranscricaoRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/configuracoes/tiktok/callback': typeof DashboardConfiguracoesTiktokCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/privacidade'
    | '/termos'
    | '/dashboard/admin'
    | '/dashboard/configuracoes'
    | '/dashboard/hashtag'
    | '/dashboard/melhores-momentos'
    | '/dashboard/planos'
    | '/dashboard/templates'
    | '/dashboard/top-players'
    | '/dashboard/transcricao'
    | '/dashboard/'
    | '/dashboard/configuracoes/tiktok/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/privacidade'
    | '/termos'
    | '/dashboard/admin'
    | '/dashboard/configuracoes'
    | '/dashboard/hashtag'
    | '/dashboard/melhores-momentos'
    | '/dashboard/planos'
    | '/dashboard/templates'
    | '/dashboard/top-players'
    | '/dashboard/transcricao'
    | '/dashboard'
    | '/dashboard/configuracoes/tiktok/callback'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/privacidade'
    | '/termos'
    | '/dashboard/admin'
    | '/dashboard/configuracoes'
    | '/dashboard/hashtag'
    | '/dashboard/melhores-momentos'
    | '/dashboard/planos'
    | '/dashboard/templates'
    | '/dashboard/top-players'
    | '/dashboard/transcricao'
    | '/dashboard/'
    | '/dashboard/configuracoes/tiktok/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  PrivacidadeRoute: typeof PrivacidadeRoute
  TermosRoute: typeof TermosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/termos': {
      id: '/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof TermosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/admin': {
      id: '/dashboard/admin'
      path: '/admin'
      fullPath: '/dashboard/admin'
      preLoaderRoute: typeof DashboardAdminRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/configuracoes': {
      id: '/dashboard/configuracoes'
      path: '/configuracoes'
      fullPath: '/dashboard/configuracoes'
      preLoaderRoute: typeof DashboardConfiguracoesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/hashtag': {
      id: '/dashboard/hashtag'
      path: '/hashtag'
      fullPath: '/dashboard/hashtag'
      preLoaderRoute: typeof DashboardHashtagRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/melhores-momentos': {
      id: '/dashboard/melhores-momentos'
      path: '/melhores-momentos'
      fullPath: '/dashboard/melhores-momentos'
      preLoaderRoute: typeof DashboardMelhoresMomentosRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/planos': {
      id: '/dashboard/planos'
      path: '/planos'
      fullPath: '/dashboard/planos'
      preLoaderRoute: typeof DashboardPlanosRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/templates': {
      id: '/dashboard/templates'
      path: '/templates'
      fullPath: '/dashboard/templates'
      preLoaderRoute: typeof DashboardTemplatesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/top-players': {
      id: '/dashboard/top-players'
      path: '/top-players'
      fullPath: '/dashboard/top-players'
      preLoaderRoute: typeof DashboardTopPlayersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/transcricao': {
      id: '/dashboard/transcricao'
      path: '/transcricao'
      fullPath: '/dashboard/transcricao'
      preLoaderRoute: typeof DashboardTranscricaoRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/configuracoes/tiktok/callback': {
      id: '/dashboard/configuracoes/tiktok/callback'
      path: '/tiktok/callback'
      fullPath: '/dashboard/configuracoes/tiktok/callback'
      preLoaderRoute: typeof DashboardConfiguracoesTiktokCallbackRouteImport
      parentRoute: typeof DashboardConfiguracoesRoute
    }
  }
}

interface DashboardConfiguracoesRouteChildren {
  DashboardConfiguracoesTiktokCallbackRoute: typeof DashboardConfiguracoesTiktokCallbackRoute
}

const DashboardConfiguracoesRouteChildren: DashboardConfiguracoesRouteChildren =
  {
    DashboardConfiguracoesTiktokCallbackRoute:
      DashboardConfiguracoesTiktokCallbackRoute,
  }

const DashboardConfiguracoesRouteWithChildren =
  DashboardConfiguracoesRoute._addFileChildren(
    DashboardConfiguracoesRouteChildren,
  )

interface DashboardRouteChildren {
  DashboardAdminRoute: typeof DashboardAdminRoute
  DashboardConfiguracoesRoute: typeof DashboardConfiguracoesRouteWithChildren
  DashboardHashtagRoute: typeof DashboardHashtagRoute
  DashboardMelhoresMomentosRoute: typeof DashboardMelhoresMomentosRoute
  DashboardPlanosRoute: typeof DashboardPlanosRoute
  DashboardTemplatesRoute: typeof DashboardTemplatesRoute
  DashboardTopPlayersRoute: typeof DashboardTopPlayersRoute
  DashboardTranscricaoRoute: typeof DashboardTranscricaoRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAdminRoute: DashboardAdminRoute,
  DashboardConfiguracoesRoute: DashboardConfiguracoesRouteWithChildren,
  DashboardHashtagRoute: DashboardHashtagRoute,
  DashboardMelhoresMomentosRoute: DashboardMelhoresMomentosRoute,
  DashboardPlanosRoute: DashboardPlanosRoute,
  DashboardTemplatesRoute: DashboardTemplatesRoute,
  DashboardTopPlayersRoute: DashboardTopPlayersRoute,
  DashboardTranscricaoRoute: DashboardTranscricaoRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  PrivacidadeRoute: PrivacidadeRoute,
  TermosRoute: TermosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
